rvm: 
  - 2.1.1

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

notifications:
  irc: "irc.freenode.org#slab"

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec

before_script:
  - mysql -e 'create database prism_test'
  - psql -c 'create database prism_test' -U postgres

